// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdrppadworepxgdlhybu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kcnBwYWR3b3JlcHhnZGxoeWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxMzcyMDksImV4cCI6MjA5MDcxMzIwOX0.1YWgvKL3tnXNbLCk5na5-C7c7dQndLOnfJAFznl0uzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
